kafka:
  bootstrap-servers: localhost:9092

logging:
  level:
    ROOT: debug


management:
  jmx:
    enabled: true
    unique-names: true
  jolokia:
    enabled: true
  endpoints:
    web:
      exposure:
        include: *

spring:
  jmx:
    enabled: true
    unique-names: true


