apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-cli
  name: ksql-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksql-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-cli
    spec:
      containers:
      - command:
        - /bin/sh
        image: confluentinc/cp-ksql-cli:5.4.0
        imagePullPolicy: ""
        name: ksql-cli
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
