version: '3'

services:
  lg-west-1:
    image: opentsx/time-series-generator:3.0.0
    hostname: lg-west-1
    container_name: lg-west-1
    networks:
      - n1
    volumes:
      - ./config/:/etc/opentsx/config/
      - ./bin/:/opentsx-lg/bin/
    environment:
      OPENTSX_TOPIC_MAP_FILE_NAME: "/etc/opentsx/config/topiclist.def"
      #OPENTSX_PRIMARY_CLUSTER_CLIENT_CFG_FILE_NAME: "/etc/opentsx/config/cpl.props"
      OPENTSX_PRIMARY_CLUSTER_CLIENT_CFG_FILE_NAME: "/etc/opentsx/config/cuh.props"
      OPENTSX_SHOW_GUI: "false"
    extra_hosts:
      - "broker-west-5:192.168.0.9"
      - "broker-west-6:192.168.0.9"
      - "broker-west-7:192.168.0.9"
      - "broker-west-1:192.168.0.6"
      - "broker-west-2:192.168.0.6"
      - "broker-east-3:192.168.0.6"
      - "broker-east-4:192.168.0.6"
      - "zookeeper-central:192.168.0.6"
      - "zookeeper-east:192.168.0.6"
      - "zookeeper-west:192.168.0.6"
      - "broker-east-8:192.169.0.11"
      - "broker-east-9:192.169.0.11"
      - "broker-east-10:192.169.0.11"
    entrypoint: /opentsx-lg/bin/executor-script.sh
    tty: false

networks:
  n1:
