---
version: '2'

services:
  ksqldb-server:
    image: confluentinc/ksqldb-server:0.11.0
    #image: confluentinc/ksqldb-server:0.10.0
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: Mirko-Kampf-MBP15.local:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://Mirko-Kampf-MBP15.local:8081
      # Configuration for UDFs
      KSQL_KSQL_EXTENSION_DIR: "/opt/ksql/ext"

    volumes:
      - /Users/mkampf/GITHUB.public/OpenTSx/opentsx-ksql-app/ksql-server-extension:/opt/ksql/ext:ro


  ksqldb-cli:
    image: confluentinc/ksqldb-cli:latest
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true