## Configuration file for the Krake Garbage Collector

api_endpoint: http://Mirko-Kampf-MBP15.local:8080
worker_count: 5
debounce: 1.0
tls:
  enabled: false
  client_ca: tmp/pki/ca.pem
  client_cert: tmp/pki/system:gc.pem
  client_key: tmp/pki/system:gc-key.pem


log:
  version: 1
  level: INFO
  disable_existing_loggers: false
  formatters:
    krake:
      format: "%(asctime)s - [%(name)s] - [%(levelname)-5s] - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: krake
      stream: ext://sys.stdout
    file:
      class: logging.handlers.WatchedFileHandler
      formatter: krake
      filename: krake.log
  root: # Configuring the default (root) logger is highly recommended
    handlers: [console]
  loggers:
    krake:
      handlers: [console]
      propagate: no
